server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  application:
    name: AttendeeService

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: attendee-group

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: eventpro
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: false
      properties:
        hibernate:
          highlight_sql: true
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
          type:
            trace: true

  security:
    oauth2:
      client:
        registration:
          attendee-client:
            authorization-grant-type: client_credentials
            client-id: attendee-client
            client-secret: rQuAVr5dBhzDCyKoDS2ngIsvFe1CymHP
            provider: attendee-provider
            scope: openid
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
        provider:
          attendee-provider:
            authorization-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/auth
            token-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            user-info-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/master/protocol/openid-connect/certs

kafka:
  topic:
    payment: 
      success: payment.success 
    ticket:
      sale:
        done: ticket.sale.done
    participant:
      checkin: participant.checked.in
